# apiVersion: v1
# kind: Service
# metadata:
#   name: config-server-node-port
# spec:
#   type: NodePort
#   ports:
#     - port: 8085
#       targetPort: 8085
#       nodePort: 30000
#   selector:
#     ors: config-server