apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      ors: zipkin
  template:
    metadata:
      labels:
        ors: zipkin
    spec:
      containers:
        - name: zipkin
          image: openzipkin/zipkin:latest
          ports:
            - containerPort: 9411

---
apiVersion: v1
kind: Service
metadata:
  name: zipkin-service
spec:
  type: LoadBalancer
  selector:
    ors: zipkin
  ports:
    - protocol: TCP
      port: 9411
      targetPort: 9411