apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeper-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      ors: zookeeper
  template:
    metadata:
      labels:
        ors: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: bitnami/zookeeper:latest
          ports:
            - containerPort: 2181
          env:
            - name: ZOO_ENABLE_AUTH
              value: 'yes'
            - name: ZOO_SERVER_USERS
              valueFrom:
                configMapKeyRef:
                  name: ors-configmap
                  key: ZOO_SERVER_USERS
            - name: ZOO_SERVER_PASSWORDS
              valueFrom:
                configMapKeyRef:
                  name: ors-configmap
                  key: ZOO_SERVER_PASSWORDS

---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-clusterip-service
spec:
  type: ClusterIP
  selector:
    ors: zookeeper
  ports:
    - port: 2181
      targetPort: 2181