apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      ors: mongodb
  template:
    metadata:
      labels:
        ors: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongodb/ors
          ports:
            - containerPort: 27017

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-clusterip-service
  spec:
    type: ClusterIP
    selector:
      ors: mongodb
    ports:
      - port: 27017
        targetPort: 27017