apiVersion: v1
kind: Service
metadata:
  name: customer-application-clusterip-service
  spec:
    type: ClusterIP
    selector:
      ors: customer-application-deployment
    ports:
      - port: 8095
        targetPort: 8095