---
# Install java using generic method irrespective of apt or yum

- name: Install java, maven pakages using generic method
  become: yes
  become_method: sudo
  package:
    name: 
      - "openjdk-{{ java_version }}-jdk"
      - maven
    state: latest
    force: yes
    purge: yes

- name: Set JAVA_HOME path to /usr/lib/jvm/java-{{ java_version }}-openjdk-amd64
  become: yes
  become_method: sudo
  lineinfile:
    path: /etc/profile
    line: '{{ item }}'
  with_items:
    - "export JAVA_HOME=/usr/lib/jvm/java-{{ java_version }}-openjdk-amd64"
    - "export PATH=$PATH:$JAVA_HOME/bin"