apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      ors: grafana
  template:
    metadata:
      labels:
        ors: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:latest
          ports:
            - containerPort: 3000
          env:
            - name: GF_SECURITY_ADMIN_USER
              valueFrom:
                configMapKeyRef:
                  name: ors-configmap
                  key: GF_SECURITY_ADMIN_USER
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: ors-configmap
                  key: GF_SECURITY_ADMIN_PASSWORD

---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
spec:
  type: LoadBalancer
  selector:
    ors: grafana
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000