version: "3.8"

services:
  zipkin:
    image: openzipkin/zipkin
    mem_limit: 700m
    ports:
      - "9411:9411"
    networks:
      - ors-net

  config-server:
    image: samarthhegde24/config-server:latest
    mem_limit: 700m
    ports:
      - "8085:8085"
    networks:
      - ors-net
    depends_on:
      - zipkin

  eureka-discovery-server:
    image: samarthhegde24/eureka-discovery-server:latest
    mem_limit: 700m
    ports:
      - "8761:8761"
    networks:
      - ors-net
    depends_on:
      - zipkin
      - config-server
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_APPLICATION_NAME: ORS-Eureka-Discovery-Server
      SPRING_PROFILES_ACTIVE: default

  postgresql:
    image: samarthhegde24/postgresql:latest
    mem_limit: 700m
    ports:
      - "5432:5432"
    networks:
      - ors-net

  mongodb:
    image: samarthhegde24/mongodb:latest
    mem_limit: 700m
    ports:
      - "27017:27017"
    networks:
      - ors-net

  zookeeper:
    image: samarthhegde24/zookeeper:latest
    mem_limit: 700m
    ports:
      - "2181:2181"
    networks:
      - ors-net

  kafka:
    image: kafka/ors:latest
    mem_limit: 700m
    ports:
      - "9092:9092"
    networks:
      - ors-net
    depends_on:
      - zookeeper
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  customer-application:
    image: samarthhegde24/customer-application:latest
    mem_limit: 700m
    ports:
      - "8095:8095"
    networks:
      - ors-net
    depends_on:
      - zipkin
      - config-server
      - postgresql
      - eureka-discovery-server
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default

  product-application:
    image: samarthhegde24/product-applcation:latest
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - ors-net
    depends_on:
      - zipkin
      - config-server
      - mongodb
      - eureka-discovery-server
      - kafka
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default

  orders-application:
    image: samarthhegde24/orders-application:latest
    mem_limit: 700m
    ports:
      - "8100:8100"
    networks:
      - ors-net
    depends_on:
      - zipkin
      - config-server
      - mongodb
      - kafka
      - eureka-discovery-server
      - product-application
      - customer-application
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default

  edge-eureka-client:
    image: samarthhegde24/edge-eureka-client:latest
    mem_limit: 700m
    ports:
      - "8088:8088"
    networks:
      - ors-net
    depends_on:
      - zipkin
      - config-server
      - eureka-discovery-server
      - product-application
      - customer-application
      - orders-application
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default


networks:
  ors-net: