version: "3.8"

services:
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - ors-net

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
    networks:
      - ors-net
    depends_on:
      - prometheus

  zipkin:
    image: openzipkin/zipkin
    mem_limit: 700m
    ports:
      - "9411:9411"
    networks:
      - ors-net

  config-server:
    image: config-server/ors:latest
    mem_limit: 700m
    ports:
      - "8085:8085"
    networks:
      - ors-net
    depends_on:
      - zipkin

  eureka-discovery-server:
    image: eureka-discovery-server/ors:latest
    mem_limit: 700m
    ports:
      - "8761:8761"
    networks:
      - ors-net
    depends_on:
      - zipkin
      - config-server
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_APPLICATION_NAME: ORS-Eureka-Discovery-Server
      SPRING_PROFILES_ACTIVE: default

  postgresql:
    image: postgres:14
    mem_limit: 700m
    ports:
      - "5432:5432"
    networks:
      - ors-net
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "tiger"
      POSTGRES_DB: "orsdb_customers"

  mongodb:
    image: mongo:5-focal
    mem_limit: 700m
    ports:
      - "27017:27017"
    networks:
      - ors-net

  zookeeper:
    image: bitnami/zookeeper:latest
    mem_limit: 700m
    ports:
      - "2181:2181"
    networks:
      - ors-net
    environment:
      ZOO_ENABLE_AUTH: "yes"
      ZOO_SERVER_USERS: "zookeeper"
      ZOO_SERVER_PASSWORDS: "zookeeper"

  kafka:
    image: bitnami/kafka:latest
    mem_limit: 700m
    ports:
      - "9092:9092"
    networks:
      - ors-net
    depends_on:
      - zookeeper
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      ALLOW_PLAINTEXT_LISTENER: "yes"
      BITNAMI_APP_NAME: "kafka"
      KAFKA_BROKER_PASSWORD: "bitnami"
      KAFKA_BROKER_USER: "user"
      KAFKA_CERTIFICATE_PASSWORD: ""
      KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://:9092"
      KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092"
      KAFKA_CFG_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_INTER_BROKER_PASSWORD: "bitnami"
      KAFKA_INTER_BROKER_USER: "admin"
      KAFKA_PORT_NUMBER: "9092"
      KAFKA_ZOOKEEPER_PASSWORD: "zookeeper"
      KAFKA_ZOOKEEPER_USER: "zookeeper"

  customer-application:
    image: customer-application/ors:latest
    mem_limit: 700m
    ports:
      - "8095:8095"
    networks:
      - ors-net
    depends_on:
      - zipkin
      - config-server
      - postgresql
      - eureka-discovery-server
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default

  product-application:
    image: product-application/ors:latest
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - ors-net
    depends_on:
      - zipkin
      - config-server
      - mongodb
      - eureka-discovery-server
      - kafka
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default

  orders-application:
    image: orders-application/ors:latest
    mem_limit: 700m
    ports:
      - "8100:8100"
    networks:
      - ors-net
    depends_on:
      - zipkin
      - config-server
      - mongodb
      - kafka
      - eureka-discovery-server
      - product-application
      - customer-application
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default

  edge-eureka-client:
    image: edge-eureka-client/ors:latest
    mem_limit: 700m
    ports:
      - "8088:8088"
    networks:
      - ors-net
    depends_on:
      - zipkin
      - config-server
      - eureka-discovery-server
      - product-application
      - customer-application
      - orders-application
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default


networks:
  ors-net: