apiVersion: v1
kind: ConfigMap
metadata:
  name: ors-configmap
data:
  ZIPKIN_URL: http://zipkin-service:9411/
  GF_SECURITY_ADMIN_USER: admin
  GF_SECURITY_ADMIN_PASSWORD: password
  CONFIG_GIT_URL: https://github.com/samarthhegde248/ORS-Config-Server.git
  CLOUD_CONFIG_URI: http://config-server-clusterip-service:8085
  EUREKA_SERVER_URL: http://eureka-discovery-server-clusterip-service:8761/eureka
  LOG_FILE_PATH: /var/log/ORS
  PATH_TO_ORS_APP: /usr/ORS
  CUSTOMERS_POSTGRESQL_DB_NAME: orsdb_customers
  ORDERS_MONGO_DB_NAME: orsdb_orders
  PRODUCTS_MONGO_DB_NAME: orsdb_products
  POSTGRESQL_DB_TYPE: postgresql
  POSTGRESQL_DB_HOST: postgresql-clusterip-service
  POSTGRESQL_DB_PORT: '5432'
  POSTGRESQL_DB_USERNAME: postgres
  POSTGRESQL_DB_PASSWORD: tiger
  ZOO_SERVER_USERS: zookeeper
  ZOO_SERVER_PASSWORDS: zookeeper
  KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper-clusterip-service:2181
  MONGO_DB_TYPE: mongodb
  MONGO_DB_HOST: mongodb-clusterip-service
  MONGO_DB_PORT: '27017'
  MONGO_DB_USERNAME: ''
  MONGO_DB_PASSWORD: ''
  KAFKA_SERVERS: kafka-clusterip-service:9092